version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: finance_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_php
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: finance_mysql
    environment:
      MYSQL_DATABASE: finance
      MYSQL_USER: finance_user
      MYSQL_PASSWORD: finance_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
